/**
 * Writes .env.local from the running local Supabase stack (`npm run db:start` first).
 *
 *   npm run env:local            # create .env.local (refuses to overwrite)
 *   npm run env:local -- --force # overwrite
 *
 * The values written are the standard keys of the local development stack. They only work against
 * your own machine and are not secrets, but .env.local is git-ignored regardless.
 */
import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const target = resolve(process.cwd(), ".env.local");
const force = process.argv.includes("--force");

if (existsSync(target) && !force) {
  console.error(".env.local already exists. Re-run with --force to overwrite it.");
  process.exit(1);
}

let output: string;
try {
  output = execFileSync("npx", ["supabase", "status", "-o", "env"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
} catch {
  console.error(
    "Could not read the local Supabase status. Is the stack running? Start it with: npm run db:start",
  );
  process.exit(1);
}

const values = new Map<string, string>();
for (const line of output.split("\n")) {
  const match = /^([A-Z_]+)="?(.*?)"?$/.exec(line.trim());
  if (match?.[1] && match[2] !== undefined) values.set(match[1], match[2]);
}

const url = values.get("API_URL");
const anon = values.get("ANON_KEY");
const service = values.get("SERVICE_ROLE_KEY");
if (!url || !anon || !service) {
  console.error(
    "Unexpected `supabase status` output; could not find API_URL / ANON_KEY / SERVICE_ROLE_KEY.",
  );
  process.exit(1);
}

const lines = [
  "# Generated by `npm run env:local` for the LOCAL Supabase stack. Git-ignored.",
  `SUPABASE_URL=${url}`,
  `SUPABASE_ANON_KEY=${anon}`,
  `SUPABASE_SERVICE_ROLE_KEY=${service}`,
  "SITE_URL=http://localhost:3000",
  "",
  "# Optional: automation (n8n) dispatcher. Leave blank to keep the integration disabled.",
  `CRON_SECRET=${randomBytes(24).toString("hex")}`,
  "N8N_WEBHOOK_URL=",
  "N8N_WEBHOOK_SECRET=",
  "",
];

writeFileSync(target, lines.join("\n"), { mode: 0o600 });
console.log(`Wrote ${target}`);
